# Generated by Django 2.1 on 2018-08-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20180818_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecamp',
            name='clothing_recieved_number',
            field=models.TextField(blank=True, null=True, verbose_name='clothing recieved- ഭക്ഷണം'),
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='clothing_required_number',
            field=models.TextField(blank=True, null=True, verbose_name='clothing required- ഭക്ഷണം'),
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='food_recieved_number',
            field=models.TextField(blank=True, null=True, verbose_name='Food recieved- ഭക്ഷണം'),
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='food_required_number',
            field=models.TextField(blank=True, null=True, verbose_name='Food required- ഭക്ഷണം'),
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='sanitary_recieved_number',
            field=models.TextField(blank=True, null=True, verbose_name='sanitary recieved- ഭക്ഷണം'),
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='sanitary_required_number',
            field=models.TextField(blank=True, null=True, verbose_name='sanitary required- ഭക്ഷണം'),
        ),
    ]
